#!/usr/bin/env bash
# ============================================================================
# tests/run.sh — Node test runner for the Foraxx Palette Studio PJSR libraries
# ============================================================================
#
# PixInsight scripts cannot run headless, so the strategy is:
#   1. strip the PixInsight preprocessor lines (#feature-id, #include, #define
#      with line continuations) from the lib files;
#   2. build tests/build/module.js: the stripped pure-logic libs concatenated,
#      a shim for the PixInsight globals they touch, and a module.exports block
#      exposing the expression builders and the style table;
#   3. syntax-check that exact file with node --check, then run every
#      tests/*.test.js against it;
#   4. syntax-check every PJSR file that is NOT bundled — the entry script and
#      the PI-facing libs — with the same strip.
#
# What is covered here is the expression layer: the PixelMath strings that
# decide what every user's image comes out looking like. The PI-facing halves
# (dialog, preview render, processing) are exercised by hand in PixInsight.
#
# Usage: bash tests/run.sh
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/tests/build"
MODULE="$BUILD/module.js"

# Libs the harness loads and drives, in dependency order: FXExpressions reads
# fxStyle/FXStyles, FXProcessing reads both. FXProcessing is full of PI-facing
# code, but it loads under the shim and its conditioning maths - the part that
# decides how dark an image comes out - is plain arithmetic worth testing.
LIBS=(
   "$ROOT/pjsr/lib/FXParameters.js"
   "$ROOT/pjsr/lib/FXStrings.js"
   "$ROOT/pjsr/lib/FXExpressions.js"
   "$ROOT/pjsr/lib/FXProcessing.js"
)

# Files the harness only parses: they build PixInsight controls at load time.
UNBUNDLED=(
   "$ROOT/pjsr/ForaxxPaletteStudio.js"
   "$ROOT/pjsr/lib/FXDialog.js"
   "$ROOT/pjsr/lib/FXHistogram.js"
   "$ROOT/pjsr/lib/FXPreview.js"
   "$ROOT/pjsr/lib/FXSplitter.js"
)

# Strip PI preprocessor directives, including backslash-continued ones, and CR
# line endings; the lib files are plain JavaScript otherwise.
strip() {
   # #__FILE__ is a preprocessor token used mid-expression, which a line-based
   # strip cannot see and node cannot parse. Rewrite it to a string literal
   # first, then drop the directive lines.
   sed -e 's/#__FILE__/"__FILE__"/g' "$1" |
      awk '{ sub(/\r$/,"") } cont { cont = /\\$/; next } /^[[:space:]]*#/ { cont = /\\$/; next } { print }'
}

mkdir -p "$BUILD"

{
   echo '// Generated by tests/run.sh — do not edit'
   cat "$ROOT/tests/shim.js"
   for lib in "${LIBS[@]}"; do
      echo "// ---- $(basename "$lib") ----"
      strip "$lib"
   done
   cat <<'EOF'

module.exports = {
   // --- parameters -------------------------------------------------------
   FXStyles: FXStyles,
   FX: FX,
   FXDefaults: FXDefaults,
   FXPersisted: FXPersisted,
   FXRanges: FXRanges,
   FX_LEVEL_SETS: FX_LEVEL_SETS,
   fxStyle: fxStyle,
   fxFirstStyleFor: fxFirstStyleFor,
   fxLevelsAreIdentity: fxLevelsAreIdentity,

   // The defensive layer over every settings file and process icon in the
   // field. It had no assertions at all, and needed nothing but this line.
   FX_UI: FX_UI,
   fxT: fxT,
   fxSanitize: fxSanitize,
   fxApplyStyle: fxApplyStyle,
   fxResetAllLevels: fxResetAllLevels,
   fxMigrateHdrEnabled: fxMigrateHdrEnabled,
   fxMigratePaletteBlend: fxMigratePaletteBlend,
   fxMigratePreviewTarget: fxMigratePreviewTarget,

   // --- expressions ------------------------------------------------------
   fxNum: fxNum,
   fxMTF: fxMTF,
   fxStretch: fxStretch,
   fxGain: fxGain,
   fxDynamicFactor: fxDynamicFactor,
   fxBlendByMask: fxBlendByMask,
   fxMix: fxMix,
   fxPrepareChannels: fxPrepareChannels,
   fxBuildExpressions: fxBuildExpressions,
   fxBuildStarStretchExpression: fxBuildStarStretchExpression,
   fxBuildStarRGBExpressions: fxBuildStarRGBExpressions,
   fxBuildPosteriseExpressions: fxBuildPosteriseExpressions,
   fxBuildHDRCompression: fxBuildHDRCompression,
   fxBuildLuminanceApplyExpressions: fxBuildLuminanceApplyExpressions,
   fxBuildCombineExpression: fxBuildCombineExpression,
   FX_STAR_HA_TO_OIII: FX_STAR_HA_TO_OIII,

   // --- processing: conditioning maths and identifier helpers -------------
   fxClamp: fxClamp,
   fxMTFValue: fxMTFValue,
   fxSolveMTF: fxSolveMTF,
   fxChannelStats: fxChannelStats,
   fxClearStatsCache: fxClearStatsCache,
   fxBlackPointFor: fxBlackPointFor,
   fxMedianAfterBlackPoint: fxMedianAfterBlackPoint,
   fxNormalizationBoost: fxNormalizationBoost,
   fxChannelTransform: fxChannelTransform,
   fxStretchMapFor: fxStretchMapFor,
   fxCollectStretch: fxCollectStretch,
   fxLooksLinear: fxLooksLinear,
   fxUniqueViewId: fxUniqueViewId,
   fxUniqueBaseId: fxUniqueBaseId,
   fxScaleCurve: fxScaleCurve,
   fxScaleDeltaCurve: fxScaleDeltaCurve,

   // --- shim handles, for driving the above ------------------------------
   fxTestView: fxTestView,
   fxTestSetViews: fxTestSetViews,
   fxTestConsole: fxTestConsole,
   fxTestConsoleReset: fxTestConsoleReset
};
EOF
} > "$MODULE"

node --check "$MODULE"
echo "OK   syntax (node --check, bundled)"

for src in "${UNBUNDLED[@]}"; do
   out="$BUILD/check-$(basename "$src")"
   { echo "// Generated by tests/run.sh — do not edit"; strip "$src"; } > "$out"
   node --check "$out"
   echo "OK   syntax $(basename "$src") (node --check, unbundled)"
done

failures=0
total=0
for t in "$ROOT"/tests/*.test.js; do
   if node "$t" > "$BUILD/last.log" 2>&1; then
      # A zero exit is necessary but not sufficient. The suite must also have
      # said how many assertions it ran, in the exact form report() emits: a
      # suite that stopped asserting, or returned early, exits 0 with nothing to
      # show, and that must not read as success.
      summary="$(grep -E '^[a-z0-9_-]+: [0-9]+ assertions passed\.$' "$BUILD/last.log" | tail -1)"
      if [ -z "$summary" ]; then
         echo "FAIL $(basename "$t") exited 0 without reporting an assertion count"
         cat "$BUILD/last.log"
         failures=1
         continue
      fi
      n="$(printf '%s' "$summary" | grep -oE '[0-9]+ assertions' | grep -oE '[0-9]+')"
      total=$(( total + n ))
      echo "OK   $summary"
   else
      echo "FAIL $(basename "$t")"
      cat "$BUILD/last.log"
      failures=1
   fi
done

if [ "$failures" -ne 0 ]; then
   echo "Tests failed." >&2
   exit 1
fi
echo "All tests passed ($total assertions)."
