#!/usr/bin/env bash
# ============================================================================
# tests/run.sh — Node test runner for the Foraxx Palette Studio PJSR libraries
# ============================================================================
#
# PixInsight scripts cannot run headless, so the strategy is:
#   1. strip the PixInsight preprocessor lines (#feature-id, #include, #define
#      with line continuations) from the lib files;
#   2. build tests/build/module.js: the stripped pure-logic libs concatenated,
#      a shim for the PixInsight globals they touch, and a module.exports block
#      exposing the expression builders and the style table;
#   3. syntax-check that exact file with node --check, then run every
#      tests/*.test.js against it;
#   4. syntax-check every PJSR file that is NOT bundled — the entry script and
#      the PI-facing libs — with the same strip.
#
# What is covered here is the expression layer: the PixelMath strings that
# decide what every user's image comes out looking like. The PI-facing halves
# (dialog, preview render, processing) are exercised by hand in PixInsight.
#
# Usage: bash tests/run.sh
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD="$ROOT/tests/build"
MODULE="$BUILD/module.js"

# Pure-logic libs, in dependency order: FXExpressions reads fxStyle/FXStyles.
LIBS=(
   "$ROOT/pjsr/lib/FXParameters.js"
   "$ROOT/pjsr/lib/FXExpressions.js"
)

# PI-facing files: syntax only.
UNBUNDLED=(
   "$ROOT/pjsr/ForaxxPaletteStudio.js"
   "$ROOT/pjsr/lib/FXDialog.js"
   "$ROOT/pjsr/lib/FXHistogram.js"
   "$ROOT/pjsr/lib/FXPreview.js"
   "$ROOT/pjsr/lib/FXProcessing.js"
   "$ROOT/pjsr/lib/FXSplitter.js"
)

# Strip PI preprocessor directives, including backslash-continued ones, and CR
# line endings; the lib files are plain JavaScript otherwise.
strip() {
   awk '{ sub(/\r$/,"") } cont { cont = /\\$/; next } /^[[:space:]]*#/ { cont = /\\$/; next } { print }' "$1"
}

mkdir -p "$BUILD"

{
   echo '// Generated by tests/run.sh — do not edit'
   cat "$ROOT/tests/shim.js"
   for lib in "${LIBS[@]}"; do
      echo "// ---- $(basename "$lib") ----"
      strip "$lib"
   done
   cat <<'EOF'

module.exports = {
   FXStyles: FXStyles,
   FX: FX,
   FXDefaults: FXDefaults,
   fxStyle: fxStyle,
   fxFirstStyleFor: fxFirstStyleFor,
   fxNum: fxNum,
   fxMTF: fxMTF,
   fxStretch: fxStretch,
   fxGain: fxGain,
   fxDynamicFactor: fxDynamicFactor,
   fxBlendByMask: fxBlendByMask,
   fxMix: fxMix,
   fxPrepareChannels: fxPrepareChannels,
   fxBuildExpressions: fxBuildExpressions,
   fxBuildStarStretchExpression: fxBuildStarStretchExpression,
   fxBuildStarRGBExpressions: fxBuildStarRGBExpressions,
   fxBuildPosteriseExpressions: fxBuildPosteriseExpressions,
   fxBuildHDRCompression: fxBuildHDRCompression,
   fxBuildLuminanceApplyExpressions: fxBuildLuminanceApplyExpressions,
   fxBuildCombineExpression: fxBuildCombineExpression
};
EOF
} > "$MODULE"

node --check "$MODULE"
echo "OK   syntax (node --check, bundled)"

for src in "${UNBUNDLED[@]}"; do
   out="$BUILD/check-$(basename "$src")"
   { echo "// Generated by tests/run.sh — do not edit"; strip "$src"; } > "$out"
   node --check "$out"
   echo "OK   syntax $(basename "$src") (node --check, unbundled)"
done

failures=0
for t in "$ROOT"/tests/*.test.js; do
   if node "$t" > "$BUILD/last.log" 2>&1; then
      echo "OK   $(basename "$t")"
   else
      echo "FAIL $(basename "$t")"
      cat "$BUILD/last.log"
      failures=1
   fi
done

if [ "$failures" -ne 0 ]; then
   echo "Tests failed." >&2
   exit 1
fi
echo "All tests passed."
