// SPDX-License-Identifier: CC-BY-NC-4.0
#ifndef __FX_Expressions_js
#define __FX_Expressions_js

/*
 * *****************************************************************************
 *
 * FXExpressions.js - PixelMath expression builders.
 * Part of Foraxx Palette Studio.
 *
 * Every expression used by the preview and by the final render is produced
 * here, so what you see in the preview panel is generated by exactly the same
 * strings that are handed to PixelMath when you press Execute.
 *
 * -----------------------------------------------------------------------------
 * The maths
 * -----------------------------------------------------------------------------
 *
 * Optional linear pre-stretch, per channel, is the standard midtones transfer
 * function applied after a shadows clip:
 *
 *          t = max( 0, (x - c0) / (1 - c0) )
 *          y = MTF( m, t ) = (1-m)*t / (m - (2m-1)*t)
 *
 * c0 and m come from the channel's own median and MAD, exactly as PixInsight's
 * screen transfer function computes them, so an auto-stretched channel lands at
 * the requested target background.
 *
 * Channel weighting is a *soft* gain rather than a plain multiplication:
 *
 *          w(x) = g*x / (1 + (g-1)*x)
 *
 * It is monotonic, maps 0 -> 0 and 1 -> 1 exactly, has slope g at the black
 * point, and can never push a sample above 1. A plain "g*x" would clip the
 * highlights and flatten the brightest nebula cores, which is precisely the
 * kind of signal damage we are trying to avoid. At g = 1 it is the identity
 * and the expression is emitted unchanged.
 *
 * The two dynamic masks keep the original published form, with an added
 * hardness multiplier k on the exponent:
 *
 *          o  = O^(k_o  * (1-O))
 *          ho = (H*O)^(k_ho * (1-(H*O)))
 *
 * k = 1 reproduces the classic masks exactly. k > 1 makes the transition
 * later and harder, k < 1 makes it earlier and softer.
 *
 * The blend amount t interpolates between the static map and the dynamic one,
 * so t = 0 gives the plain palette and t = 1 gives full Foraxx.
 *
 * *****************************************************************************
 */

#include "FXParameters.js"

/*
 * Formats a number for embedding in a PixelMath expression. Six decimals is
 * far more than the 32-bit working precision needs and avoids any locale or
 * exponent-notation surprises.
 */
/*
 * The smallest midtones balance the pipeline will emit. The MTF is well behaved
 * for any m > 0 - its denominator is m + (1 - 2m)t, which for m < 0.5 and
 * t >= 0 can never fall below m - so the only real floor is what fxNum can
 * still write down with enough significant digits.
 */
/*
 * These two are coupled. fxNum writes FX_NUM_DECIMALS decimals for small
 * magnitudes, so FX_MTF_MIN has to stay well above 10^-FX_NUM_DECIMALS: if the
 * midtones balance ever rounded to a literal zero, the MTF denominator would be
 * 0 at t = 0 and the whole background would come out NaN, which truncation
 * cannot repair. At 1e-8 against 12 decimals there are four orders of margin.
 */
var FX_NUM_DECIMALS = 12;
var FX_MTF_MIN = 1.0e-8;

function fxNum( v )
{
   // Six decimals covers the [0, 1] range the pipeline normally works in, and
   // reproduces every expression the original script produces exactly.
   //
   // Linear data breaks that assumption. A midtones balance solved to lift a
   // sky background of 3e-5 up to 0.25 is itself of order 2.5e-5, where six
   // decimals leaves two significant figures - and an order of magnitude below
   // that, none at all. Small magnitudes therefore switch to a fixed number of
   // decimals deep enough to keep four significant figures down to FX_MTF_MIN.
   // Fixed notation rather than exponential, because PixelMath's acceptance of
   // an exponent in a literal is not something this codebase has confirmed.
   let a = Math.abs( v );
   if ( a > 0 && a < 1.0e-4 )
      return Number( v ).toFixed( FX_NUM_DECIMALS );
   return format( "%.6f", v );
}

function fxIsOne( v )
{
   return Math.abs( v - 1 ) < 1.0e-5;
}

function fxIsZero( v )
{
   return Math.abs( v ) < 1.0e-5;
}

/*
 * Midtones transfer function:
 *
 *          MTF( m, t ) = (1-m)*t / (m + (1-2m)*t)
 *
 * The denominator is written as m + ((1-m) - m)*t rather than with a separate
 * literal for 1-2m. Only two constants are then rounded to six decimals, and
 * at t = 1 the denominator collapses to exactly the numerator's coefficient,
 * so a sample of 1 maps to precisely 1 instead of drifting a micro-unit past
 * it. No unary minus ever reaches the parser either.
 */
function fxMTF( expr, m )
{
   if ( Math.abs( m - 0.5 ) < 1.0e-6 )
      return expr;
   m = Math.min( 0.999, Math.max( FX_MTF_MIN, m ) );
   let A = fxNum( 1 - m );
   let B = fxNum( m );
   return "((" + A + "*(" + expr + "))"
        + "/(" + B + " + (" + A + " - " + B + ")*(" + expr + ")))";
}

/*
 * Shadows clip followed by the midtones transfer function.
 */
function fxStretch( expr, c0, m )
{
   let t = expr;
   if ( c0 > 1.0e-6 )
   {
      // The same rounded literal has to appear in both places, otherwise
      // (1 - round(c0)) and round(1 - c0) differ in the last digit and a
      // sample of exactly 1 leaves the [0,1] range.
      let c = fxNum( c0 );
      t = "max(0,((" + expr + ") - " + c + ")/(1 - " + c + "))";
   }
   return fxMTF( t, m );
}

/*
 * Soft, highlight-preserving channel gain.
 */
function fxGain( expr, g )
{
   if ( fxIsOne( g ) )
      return expr;
   if ( g <= 0 )
      return "0";
   let d = g - 1;
   let den = (d >= 0) ? ("1 + " + fxNum( d ) + "*(" + expr + ")")
                      : ("1 - " + fxNum( -d ) + "*(" + expr + ")");
   return "((" + fxNum( g ) + "*(" + expr + "))/(" + den + "))";
}

/*
 * Dynamic PixelMath factor: base^(k*~base).
 */
function fxDynamicFactor( baseExpr, k )
{
   if ( fxIsOne( k ) )
      return "(" + baseExpr + ")^~(" + baseExpr + ")";
   return "(" + baseExpr + ")^(" + fxNum( k ) + "*~(" + baseExpr + "))";
}

/*
 * mask*hi + ~mask*lo
 */
function fxBlendByMask( maskExpr, hiExpr, loExpr )
{
   return "(" + maskExpr + ")*(" + hiExpr + ") + ~(" + maskExpr + ")*(" + loExpr + ")";
}

/*
 * Linear interpolation: t = 1 returns aExpr, t = 0 returns bExpr.
 */
function fxMix( aExpr, bExpr, t )
{
   if ( t >= 0.9999 )
      return aExpr;
   if ( t <= 0.0001 )
      return bExpr;
   return "(" + fxNum( t ) + "*(" + aExpr + ") + " + fxNum( 1 - t ) + "*(" + bExpr + "))";
}

/*
 * Turns one context into the three prepared channel expressions.
 *
 * ctx = { sii, ha, oiii, stretch: { sii: {c0,m}|null, ha: ..., oiii: ... }|null }
 *
 * Returns { S, H, O }, any of which may be null when that channel is unused.
 */
function fxPrepareChannels( p, ctx )
{
   function prepare( id, key, gain )
   {
      if ( id == null )
         return null;
      let e = id;
      if ( ctx.stretch != null && ctx.stretch[key] != null )
         e = fxStretch( e, ctx.stretch[key].c0, ctx.stretch[key].m );
      return fxGain( e, gain );
   }

   return {
      S: prepare( ctx.sii,  "sii",  p.gainSii  ),
      H: prepare( ctx.ha,   "ha",   p.gainHa   ),
      O: prepare( ctx.oiii, "oiii", p.gainOiii )
   };
}

/*
 * Builds the R/G/B expressions for one image.
 *
 * maskCtx  : the starless context - always the source of the dynamic masks,
 *            exactly as in the original script
 * valueCtx : the context supplying the pixel values; the same object as
 *            maskCtx for the starless image, the star channels for the stars
 *
 * Returns { r, g, b, o, ho }; o and ho are the mask expressions, or null in a
 * static palette mode.
 */
function fxBuildExpressions( p, maskCtx, valueCtx )
{
   let mode = fxStyle( p );
   let v = fxPrepareChannels( p, valueCtx );
   let m = fxPrepareChannels( p, maskCtx );
   let map = mode.map;

   // One branch for every palette, dynamic or fixed. The two transitions belong
   // to RGB *slots*, not to channels:
   //
   //   red   carries the Sii <-> Ha transition, gated by the Sii/Ha control
   //   green carries the Ha <-> Oiii transition, gated by the Ha/Oiii control
   //   blue  is the anchor and is never blended
   //
   // Each one is mixed towards whatever channel that slot holds in this
   // palette's mapping, by the Foraxx amount. So at amount 0 - where every
   // fixed palette starts - fxMix returns the slot's own channel and this is
   // exactly the permutation those palettes always were. At amount 1 with the
   // SHO mapping it is the published dynamic SHO character for character, and
   // with the HOO mapping the dynamic HOO, which is why raising the amount on a
   // fixed palette walks it towards its Foraxx counterpart rather than
   // somewhere else.
   //
   // Slot-wise rather than channel-wise matters for the mappings that repeat a
   // letter: in HOO the green slot holds Oiii, and it is that slot which takes
   // the Ha/Oiii blend, leaving blue's Oiii untouched. Blending per channel
   // would have driven green and blue to the same expression.
   let hoBase = "(" + m.H + ")*(" + m.O + ")";
   let ho = fxDynamicFactor( hoBase, p.hardHO );
   let o = (m.S != null && v.S != null) ? fxDynamicFactor( m.O, p.hardO ) : null;

   let base = { S: v.S, H: v.H, O: v.O };

   // With no Sii there is no Sii <-> Ha transition to make, so red is left as
   // whatever the mapping puts there.
   let r = (o == null) ? base[map[0]]
                       : fxMix( fxBlendByMask( o, v.S, v.H ), base[map[0]], p.blend );
   let g = fxMix( fxBlendByMask( ho, v.H, v.O ), base[map[1]], p.blend );
   let b = base[map[2]];

   return { r: r, g: g, b: b, o: o, ho: ho };
}



/*
 * -----------------------------------------------------------------------------
 * NB to RGB star combination
 * -----------------------------------------------------------------------------
 *
 * The published broadband star combination:
 *
 *      R = 0.5*Ha + 0.5*Sii      (0.5*Ha + 0.5*Ha when there is no Sii)
 *      G = 0.3*Ha + 0.7*Oiii    (r is fixed at 0.3, the published default)
 *      B = Oiii
 *
 * It produces far more believable star colour than running the nebula's own
 * dynamic masks over a star field, because stars are broadband sources and the
 * masks are built for line emission.
 */
var FX_STAR_HA_TO_OIII = 0.30;

/*
 * The star brightening curve, a hyperbolic stretch:
 *
 *    ((3^k) * x) / ((3^k - 1) * x + 1)
 *
 * which is the midtones transfer function with m = 1 / (1 + 3^k). It fixes 0
 * and 1 and is monotonic for every k >= 0, so it lifts faint stars hard without
 * ever clipping a bright core. 3^k is left for PixelMath to evaluate rather
 * than computed here and rounded.
 *
 * Emitted in this form rather than through fxMTF because at these strengths m
 * is tiny - 1/244 at k = 5, 1/6562 at k = 8 - and the large constant a rounds
 * far better than m does. The denominator reuses the same literal, so at x = 1
 * it collapses to 1 + (a-1) = a exactly and the expression returns exactly 1.
 *
 * k = 0 returns null - nothing to do. Be careful above about 5 on star images
 * that are already stretched: at k = 5 the multiplier is 243, and a star field
 * whose background already sits near 0.25 comes out uniformly white.
 */
function fxBuildStarStretchExpression( k )
{
   if ( fxIsZero( k ) )
      return null;
   let lo = FXRanges.starStretch[0];
   let hi = FXRanges.starStretch[1];
   let e = format( "%.2f", (k < lo) ? lo : ((k > hi) ? hi : k) );
   return "((3^" + e + ")*$T)/((3^" + e + "-1)*$T+1)";
}

function fxBuildStarRGBExpressions( p, ctx )
{
   let v = fxPrepareChannels( p, ctx );
   let red = (v.S != null) ? v.S : v.H;
   let r = FX_STAR_HA_TO_OIII;

   return {
      r: "0.5*(" + v.H + ") + 0.5*(" + red + ")",
      g: fxNum( r ) + "*(" + v.H + ") + " + fxNum( 1 - r ) + "*(" + v.O + ")",
      b: v.O,
      o: null,
      ho: null
   };
}

function fxClamp01( v )
{
   return (v < 0) ? 0 : ((v > 1) ? 1 : v);
}

/*
 * -----------------------------------------------------------------------------
 * Posterisation
 * -----------------------------------------------------------------------------
 *
 * Quantises each channel to n evenly spaced levels including 0 and 1. Flat
 * blocks of colour rather than continuous gradients - the screen-print look.
 */
function fxBuildPosteriseExpressions( levels )
{
   let n = Math.max( 2, Math.round( levels ) ) - 1;
   let expr = function( channel )
   {
      return "floor(" + channel + "*" + fxNum( n ) + " + 0.5)/" + fxNum( n );
   };
   return { r: expr( "$T[0]" ), g: expr( "$T[1]" ), b: expr( "$T[2]" ) };
}

/*
 * -----------------------------------------------------------------------------
 * Highlight compression with a knee
 * -----------------------------------------------------------------------------
 *
 * A cubic Hermite segment from the knee up to white, after the method used in
 * a knee-based curve. Below the knee nothing changes at all; above
 * it the tones are pulled back towards the knee, more strongly as the amount
 * rises. Amount 0 is exactly the identity.
 *
 * The correction is computed on luminance and applied as a single scale factor
 * to all three channels, so hue and saturation are untouched. Entirely scale
 * invariant, so the preview and the final image agree exactly.
 *
 * One deliberate difference from the source: the end slope is capped at 4
 * rather than 5. Writing the derivative as f'(t) = 1 + (3t^2 - 2t)(m1 - 1),
 * whose minimum over [0,1] is 1 - (m1-1)/3, shows the curve stops being
 * monotonic once m1 passes 4 - which inverts the upper midtones instead of
 * compressing them. At 4 the strongest setting is still exactly monotonic.
 *
 * Returned as { symbols, expression } for a single-expression PixelMath.
 */
function fxBuildHDRCompression( p )
{
   if ( fxIsZero( p.hdrAmount ) )
      return null;

   let a = fxNum( fxClamp01( p.hdrAmount ) );
   let k = fxNum( Math.min( 0.99, Math.max( 0.10, p.hdrKnee ) ) );

   return {
      symbols: "a,k,R,G,B,Y,hi,t,t2,t3,h10,h01,h11,m1,f,Yc,s",
      expression:
         "a = " + a + ";\n" +
         "k = " + k + ";\n" +
         "R = $T[0]; G = $T[1]; B = $T[2];\n" +
         "Y = 0.2126*R + 0.7152*G + 0.0722*B;\n" +
         "hi = Y > k;\n" +
         "t = min(1, max(0, (Y - k)/(1 - k)));\n" +
         "t2 = t*t;\n" +
         "t3 = t2*t;\n" +
         "h10 = (t3 - 2*t2 + t);\n" +
         "h01 = (-2*t3 + 3*t2);\n" +
         "h11 = (t3 - t2);\n" +
         "m1 = min(4, max(1, 1 + 3*a));\n" +
         "f = h10 + h01 + h11*m1;\n" +
         "Yc = k + (1 - k)*min(1, max(0, f));\n" +
         "s = iif(hi, iif(Y <= 0.0000000001, 1, Yc/Y), 1);\n" +
         "min(1, $T * s);"
   };
}


/*
 * Replaces the lightness of an RGB image with an external luminance, blended
 * by `amount`, preserving the colour ratios. Written against $T and the
 * luminance image, so it needs no extra process.
 */
function fxBuildLuminanceApplyExpressions( p, lumId )
{
   const EPS = "0.000001";
   let a = fxNum( fxClamp01( p.lumApply ) );
   let y0 = "(0.2126*$T[0] + 0.7152*$T[1] + 0.0722*$T[2])";
   let target = "((1 - " + a + ")*" + y0 + " + " + a + "*(" + lumId + "))";
   let headroom = "(1/max(max(max($T[0],$T[1]),$T[2])," + EPS + "))";
   let k = "min(" + target + "/max(" + y0 + "," + EPS + ")," + headroom + ")";

   return {
      r: "min(1,(" + k + ")*$T[0])",
      g: "min(1,(" + k + ")*$T[1])",
      b: "min(1,(" + k + ")*$T[2])"
   };
}

/*
 * Screen combination of the starless and stars images:  ~(~a * ~b)
 */
function fxBuildCombineExpression( starlessId, starsId )
{
   return "~(~" + starlessId + " * ~" + starsId + ")";
}

#endif   // __FX_Expressions_js
